"""Geometry masks, morphological cleanup, mask algebra, and mask application."""

from __future__ import annotations

from geotoolz.mask._src.array import (
    altitude_mask,
    buffer_mask,
    clean_mask,
    close_mask,
    combine_masks,
    dilate_mask,
    distance_mask,
    erode_mask,
    invert_mask,
    open_mask,
    remove_small_holes,
    remove_small_objects,
    slope_degrees,
    slope_mask,
)
from geotoolz.mask._src.operators import (
    AltitudeMask,
    ApplyMask,
    BBoxMask,
    BufferMask,
    CleanMask,
    CloseMask,
    CombineMasks,
    CountryMask,
    DilateMask,
    DistanceMask,
    ErodeMask,
    InvertMask,
    LandMask,
    OceanMask,
    OpenMask,
    PolygonMask,
    RemoveSmallHoles,
    RemoveSmallObjects,
    SlopeMask,
)


__all__ = [
    "AltitudeMask",
    "ApplyMask",
    "BBoxMask",
    "BufferMask",
    "CleanMask",
    "CloseMask",
    "CombineMasks",
    "CountryMask",
    "DilateMask",
    "DistanceMask",
    "ErodeMask",
    "InvertMask",
    "LandMask",
    "OceanMask",
    "OpenMask",
    "PolygonMask",
    "RemoveSmallHoles",
    "RemoveSmallObjects",
    "SlopeMask",
    "altitude_mask",
    "buffer_mask",
    "clean_mask",
    "close_mask",
    "combine_masks",
    "dilate_mask",
    "distance_mask",
    "erode_mask",
    "invert_mask",
    "open_mask",
    "remove_small_holes",
    "remove_small_objects",
    "slope_degrees",
    "slope_mask",
]
