"""Restoration primitives and Operators for imperfect remote-sensing data."""

from __future__ import annotations

from geotoolz.restore._src.array import (
    bilateral_denoise,
    despeckle_frost,
    despeckle_lee,
    despeckle_refined_lee,
    destripe_column,
    gap_fill_biharmonic,
    gap_fill_idw,
    gap_fill_laplacian,
    gap_fill_nearest,
    gaussian_denoise,
    median_denoise,
    nl_means,
    outlier_mask,
    pca_denoise,
    replace_outliers,
)
from geotoolz.restore._src.operators import (
    MNF,
    BilateralDenoise,
    DenoisePCA,
    DespeckleFrost,
    DespeckleLee,
    DespeckleRefinedLee,
    DestripeColumn,
    GapFillIDW,
    GapFillInpaintBiharmonic,
    GapFillLaplacian,
    GapFillNearest,
    GaussianDenoise,
    InverseMNF,
    MedianDenoise,
    MomentMatching,
    NLMeans,
    OutlierMask,
    ReplaceOutliers,
)


__all__ = [
    "MNF",
    "BilateralDenoise",
    "DenoisePCA",
    "DespeckleFrost",
    "DespeckleLee",
    "DespeckleRefinedLee",
    "DestripeColumn",
    "GapFillIDW",
    "GapFillInpaintBiharmonic",
    "GapFillLaplacian",
    "GapFillNearest",
    "GaussianDenoise",
    "InverseMNF",
    "MedianDenoise",
    "MomentMatching",
    "NLMeans",
    "OutlierMask",
    "ReplaceOutliers",
    "bilateral_denoise",
    "despeckle_frost",
    "despeckle_lee",
    "despeckle_refined_lee",
    "destripe_column",
    "gap_fill_biharmonic",
    "gap_fill_idw",
    "gap_fill_laplacian",
    "gap_fill_nearest",
    "gaussian_denoise",
    "median_denoise",
    "nl_means",
    "outlier_mask",
    "pca_denoise",
    "replace_outliers",
]
