"""geotoolz — composable Operator library for remote sensing.

Top-level re-exports of the composition core and the four-axis Patcher
framework. Domain modules (`radiometry`, `indices`, `cloud`, ...) will
sit alongside ``core`` and ``patch`` once they land — each is imported
from its own submodule.

    import geotoolz as gz
    pipe = gz.Sequential([gz.Tap(print), gz.Identity()])

    patcher = gz.SpatialPatcher(
        geometry    = gz.SpatialRectangular(size=(256, 256)),
        sampler     = gz.SpatialRegularStride(step=(192, 192)),
        window      = gz.SpatialHann(),
        aggregation = gz.SpatialOverlapAdd(),
    )
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from geotoolz import catalog, cloud, core, indices, patch, qa, radiometry, types
from geotoolz.catalog import (
    CatalogDomain,
    CatalogRow,
    GeoCatalog,
    InMemoryGeoCatalog,
    build_raster_catalog,
    from_geoparquet,
    intersect,
    load_raster,
    load_raster_timeseries,
    open_catalog,
    query,
    to_geoparquet,
    union,
)
from geotoolz.cloud import (
    SCL,
    SCL_CLOUDS,
    SCL_INVALID,
    ApplyMask,
    MaskFromQABits,
    MaskFromSCL,
    MaskValid,
)
from geotoolz.core import (
    Branch,
    Carrier,
    Const,
    Fanout,
    Graph,
    Identity,
    Input,
    Lambda,
    ModelOp,
    Node,
    Operator,
    Sequential,
    ShapeTrace,
    Sink,
    Snapshot,
    Switch,
    Tap,
)
from geotoolz.indices import (
    EVI,
    NBR,
    NDBI,
    NDVI,
    NDWI,
    SAVI,
    AppendIndex,
    NormalizedDifference,
)
from geotoolz.patch import (
    ApplyToChips,
    AsyncRasterField,
    AsyncSpatialPatcher,
    GridDomain,
    GridSampler,
    Patch,
    PointDomain,
    RasterDomain,
    RasterField,
    SpatialAggregation,
    SpatialBoxcar,
    SpatialByIndex,
    SpatialCustom,
    SpatialExplicit,
    SpatialGaussian,
    SpatialGeometry,
    SpatialHann,
    SpatialHardVote,
    SpatialInvVarWeightedMean,
    SpatialJitteredStride,
    SpatialKNNGraph,
    SpatialLearned,
    SpatialMax,
    SpatialMean,
    SpatialMedian,
    SpatialMin,
    SpatialMode,
    SpatialOverlapAdd,
    SpatialPatcher,
    SpatialPoissonDisk,
    SpatialPolygonIntersection,
    SpatialRadiusGraph,
    SpatialRandom,
    SpatialRectangular,
    SpatialRegularStride,
    SpatialSampler,
    SpatialSoftVote,
    SpatialSphericalCap,
    SpatialSum,
    SpatialTukey,
    SpatialVariance,
    SpatialWeightedSum,
    SpatialWindow,
    SpatioTemporalPatch,
    SpatioTemporalPatcher,
    Stitch,
    TemporalAggregation,
    TemporalCausalBoxcar,
    TemporalCausalRolling,
    TemporalEventTriggered,
    TemporalExplicit,
    TemporalExponentialDecay,
    TemporalFixedLookback,
    TemporalFold,
    TemporalForecast,
    TemporalGeometry,
    TemporalHierarchicalCombine,
    TemporalLookbackHorizon,
    TemporalMean,
    TemporalMultiScale,
    TemporalPatch,
    TemporalPatcher,
    TemporalPeriodic,
    TemporalPhaseWindow,
    TemporalRandom,
    TemporalRegularStride,
    TemporalSampler,
    TemporalTaperedTukey,
    TemporalWindow,
    VectorDomain,
)
from geotoolz.radiometry import (
    DNToRadiance,
    DNToReflectance,
    Gamma,
    MinMax,
    PercentileClip,
    ToFloat32,
)
from geotoolz.types import GeoSlice


if TYPE_CHECKING:
    from geotoolz.catalog import (
        DuckDBGeoCatalog,
        build_vector_catalog,
        build_xarray_catalog,
        load_vector,
        load_xarray,
    )


_LAZY_TOP_ATTRS = (
    "build_xarray_catalog",
    "load_xarray",
    "build_vector_catalog",
    "load_vector",
    "DuckDBGeoCatalog",
)


def __getattr__(name: str) -> Any:
    """Lazy proxy for the extras-gated catalog backends at the top level."""
    if name in _LAZY_TOP_ATTRS:
        attr = getattr(catalog, name)
        globals()[name] = attr
        return attr
    raise AttributeError(f"module 'geotoolz' has no attribute {name!r}")


__version__ = "0.0.5"

__all__ = [
    "EVI",
    "NBR",
    "NDBI",
    "NDVI",
    "NDWI",
    "SAVI",
    "SCL",
    "SCL_CLOUDS",
    "SCL_INVALID",
    "AppendIndex",
    "ApplyMask",
    "ApplyToChips",
    "AsyncRasterField",
    "AsyncSpatialPatcher",
    "Branch",
    "Carrier",
    "CatalogDomain",
    "CatalogRow",
    "Const",
    "DNToRadiance",
    "DNToReflectance",
    "DuckDBGeoCatalog",
    "Fanout",
    "Gamma",
    "GeoCatalog",
    "GeoSlice",
    "Graph",
    "GridDomain",
    "GridSampler",
    "Identity",
    "InMemoryGeoCatalog",
    "Input",
    "Lambda",
    "MaskFromQABits",
    "MaskFromSCL",
    "MaskValid",
    "MinMax",
    "ModelOp",
    "Node",
    "NormalizedDifference",
    "Operator",
    "Patch",
    "PercentileClip",
    "PointDomain",
    "RasterDomain",
    "RasterField",
    "Sequential",
    "ShapeTrace",
    "Sink",
    "Snapshot",
    "SpatialAggregation",
    "SpatialBoxcar",
    "SpatialByIndex",
    "SpatialCustom",
    "SpatialExplicit",
    "SpatialGaussian",
    "SpatialGeometry",
    "SpatialHann",
    "SpatialHardVote",
    "SpatialInvVarWeightedMean",
    "SpatialJitteredStride",
    "SpatialKNNGraph",
    "SpatialLearned",
    "SpatialMax",
    "SpatialMean",
    "SpatialMedian",
    "SpatialMin",
    "SpatialMode",
    "SpatialOverlapAdd",
    "SpatialPatcher",
    "SpatialPoissonDisk",
    "SpatialPolygonIntersection",
    "SpatialRadiusGraph",
    "SpatialRandom",
    "SpatialRectangular",
    "SpatialRegularStride",
    "SpatialSampler",
    "SpatialSoftVote",
    "SpatialSphericalCap",
    "SpatialSum",
    "SpatialTukey",
    "SpatialVariance",
    "SpatialWeightedSum",
    "SpatialWindow",
    "SpatioTemporalPatch",
    "SpatioTemporalPatcher",
    "Stitch",
    "Switch",
    "Tap",
    "TemporalAggregation",
    "TemporalCausalBoxcar",
    "TemporalCausalRolling",
    "TemporalEventTriggered",
    "TemporalExplicit",
    "TemporalExponentialDecay",
    "TemporalFixedLookback",
    "TemporalFold",
    "TemporalForecast",
    "TemporalGeometry",
    "TemporalHierarchicalCombine",
    "TemporalLookbackHorizon",
    "TemporalMean",
    "TemporalMultiScale",
    "TemporalPatch",
    "TemporalPatcher",
    "TemporalPeriodic",
    "TemporalPhaseWindow",
    "TemporalRandom",
    "TemporalRegularStride",
    "TemporalSampler",
    "TemporalTaperedTukey",
    "TemporalWindow",
    "ToFloat32",
    "VectorDomain",
    "__version__",
    "build_raster_catalog",
    "build_vector_catalog",
    "build_xarray_catalog",
    "catalog",
    "cloud",
    "core",
    "from_geoparquet",
    "indices",
    "intersect",
    "load_raster",
    "load_raster_timeseries",
    "load_vector",
    "load_xarray",
    "open_catalog",
    "patch",
    "qa",
    "query",
    "radiometry",
    "to_geoparquet",
    "types",
    "union",
]
