"""geotoolz — composable Operator library for remote sensing.

Top-level re-exports of the composition core and the four-axis Patcher
framework. Domain modules (`radiometry`, `indices`, `cloud`, ...) will
sit alongside ``core`` and ``patch`` once they land — each is imported
from its own submodule.

    import geotoolz as gz
    pipe = gz.Sequential([gz.Tap(print), gz.Identity()])

    patcher = gz.SpatialPatcher(
        geometry    = gz.SpatialRectangular(size=(256, 256)),
        sampler     = gz.SpatialRegularStride(step=(192, 192)),
        window      = gz.SpatialHann(),
        aggregation = gz.SpatialOverlapAdd(),
    )
"""

from __future__ import annotations

from geotoolz import core, patch
from geotoolz.core import (
    Branch,
    Carrier,
    Const,
    Fanout,
    Graph,
    Identity,
    Input,
    Lambda,
    ModelOp,
    Node,
    Operator,
    Sequential,
    ShapeTrace,
    Sink,
    Snapshot,
    Switch,
    Tap,
)
from geotoolz.patch import (
    ApplyToChips,
    AsyncRasterField,
    AsyncSpatialPatcher,
    GridDomain,
    GridSampler,
    Patch,
    PointDomain,
    RasterDomain,
    RasterField,
    SpatialAggregation,
    SpatialBoxcar,
    SpatialByIndex,
    SpatialCustom,
    SpatialExplicit,
    SpatialGaussian,
    SpatialGeometry,
    SpatialHann,
    SpatialHardVote,
    SpatialInvVarWeightedMean,
    SpatialJitteredStride,
    SpatialKNNGraph,
    SpatialLearned,
    SpatialMax,
    SpatialMean,
    SpatialMedian,
    SpatialMin,
    SpatialMode,
    SpatialOverlapAdd,
    SpatialPatcher,
    SpatialPoissonDisk,
    SpatialPolygonIntersection,
    SpatialRadiusGraph,
    SpatialRandom,
    SpatialRectangular,
    SpatialRegularStride,
    SpatialSampler,
    SpatialSoftVote,
    SpatialSphericalCap,
    SpatialSum,
    SpatialTukey,
    SpatialVariance,
    SpatialWeightedSum,
    SpatialWindow,
    SpatioTemporalPatch,
    SpatioTemporalPatcher,
    Stitch,
    TemporalAggregation,
    TemporalCausalBoxcar,
    TemporalCausalRolling,
    TemporalEventTriggered,
    TemporalExplicit,
    TemporalExponentialDecay,
    TemporalFixedLookback,
    TemporalFold,
    TemporalForecast,
    TemporalGeometry,
    TemporalHierarchicalCombine,
    TemporalLookbackHorizon,
    TemporalMean,
    TemporalMultiScale,
    TemporalPatch,
    TemporalPatcher,
    TemporalPeriodic,
    TemporalPhaseWindow,
    TemporalRandom,
    TemporalRegularStride,
    TemporalSampler,
    TemporalTaperedTukey,
    TemporalWindow,
    VectorDomain,
)


__version__ = "0.0.3"

__all__ = [
    "ApplyToChips",
    "AsyncRasterField",
    "AsyncSpatialPatcher",
    "Branch",
    "Carrier",
    "Const",
    "Fanout",
    "Graph",
    "GridDomain",
    "GridSampler",
    "Identity",
    "Input",
    "Lambda",
    "ModelOp",
    "Node",
    "Operator",
    "Patch",
    "PointDomain",
    "RasterDomain",
    "RasterField",
    "Sequential",
    "ShapeTrace",
    "Sink",
    "Snapshot",
    "SpatialAggregation",
    "SpatialBoxcar",
    "SpatialByIndex",
    "SpatialCustom",
    "SpatialExplicit",
    "SpatialGaussian",
    "SpatialGeometry",
    "SpatialHann",
    "SpatialHardVote",
    "SpatialInvVarWeightedMean",
    "SpatialJitteredStride",
    "SpatialKNNGraph",
    "SpatialLearned",
    "SpatialMax",
    "SpatialMean",
    "SpatialMedian",
    "SpatialMin",
    "SpatialMode",
    "SpatialOverlapAdd",
    "SpatialPatcher",
    "SpatialPoissonDisk",
    "SpatialPolygonIntersection",
    "SpatialRadiusGraph",
    "SpatialRandom",
    "SpatialRectangular",
    "SpatialRegularStride",
    "SpatialSampler",
    "SpatialSoftVote",
    "SpatialSphericalCap",
    "SpatialSum",
    "SpatialTukey",
    "SpatialVariance",
    "SpatialWeightedSum",
    "SpatialWindow",
    "SpatioTemporalPatch",
    "SpatioTemporalPatcher",
    "Stitch",
    "Switch",
    "Tap",
    "TemporalAggregation",
    "TemporalCausalBoxcar",
    "TemporalCausalRolling",
    "TemporalEventTriggered",
    "TemporalExplicit",
    "TemporalExponentialDecay",
    "TemporalFixedLookback",
    "TemporalFold",
    "TemporalForecast",
    "TemporalGeometry",
    "TemporalHierarchicalCombine",
    "TemporalLookbackHorizon",
    "TemporalMean",
    "TemporalMultiScale",
    "TemporalPatch",
    "TemporalPatcher",
    "TemporalPeriodic",
    "TemporalPhaseWindow",
    "TemporalRandom",
    "TemporalRegularStride",
    "TemporalSampler",
    "TemporalTaperedTukey",
    "TemporalWindow",
    "VectorDomain",
    "__version__",
    "core",
    "patch",
]
