"""geotoolz — composable Operator library for remote sensing.

Top-level re-exports of the composition core and the per-domain
operator families (`radiometry`, `indices`, `cloud`, ...) — each
imported from its own submodule.

    import geotoolz as gz
    pipe = gz.Sequential([gz.Tap(print), gz.Identity()])

The four-axis Patcher framework lives in the standalone
[`geopatcher`](https://github.com/jejjohnson/geopatcher) package. Install
the optional `[patch]` extra (``pip install 'geotoolz[patch]'``) to pull
it in and use ``geotoolz.patch_ops`` for the Operator-graph bridge:

    import geopatcher as gp
    from geotoolz import Sequential
    from geotoolz.patch_ops import GridSampler, ApplyToChips, Stitch
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from geotoolz import (
    augment,
    catalog,
    cloud,
    core,
    geom,
    indices,
    io,
    mask,
    normalize,
    plume,
    qa,
    radiometry,
    restore,
    spectral,
    types,
    viz,
)
from geotoolz.catalog import (
    CatalogDomain,
    CatalogRow,
    GeoCatalog,
    InMemoryGeoCatalog,
    build_raster_catalog,
    from_geoparquet,
    intersect,
    load_raster,
    load_raster_timeseries,
    open_catalog,
    query,
    to_geoparquet,
    union,
)
from geotoolz.cloud import (
    SCL,
    SCL_CLOUDS,
    SCL_INVALID,
    ApplyMask,
    MaskFromQABits,
    MaskFromSCL,
    MaskValid,
)
from geotoolz.core import (
    Branch,
    Carrier,
    Const,
    Fanout,
    Graph,
    Identity,
    Input,
    Lambda,
    ModelOp,
    Node,
    Operator,
    Sequential,
    ShapeTrace,
    Sink,
    Snapshot,
    Switch,
    Tap,
)
from geotoolz.indices import (
    ARVI,
    BAIS2,
    BSI,
    CIRI,
    EVI,
    EVI2,
    GCI,
    MNDWI,
    NBR,
    NBR2,
    NDBI,
    NDMI,
    NDSI,
    NDVI,
    NDWI,
    SAVI,
    AppendIndex,
    ClayMinerals,
    IronOxide,
    NormalizedDifference,
    dNBR,
    kNDVI,
)
from geotoolz.plume import (
    SBMP,
    ColumnToMass,
    CrossSectionalFlux,
    IMEEstimate,
    PlumeContours,
    PlumeFootprint,
    PlumeMask,
    WindAdvectionCone,
)
from geotoolz.radiometry import (
    DOS1,
    ApplySRF,
    BTFromRadiance,
    ComputeSZA,
    DNToRadiance,
    DNToReflectance,
    EarthSunDistanceCorrection,
    Gamma,
    IntegratedIrradiance,
    MinMax,
    PercentileClip,
    RadianceToDN,
    RadianceToReflectance,
    ReflectanceToRadiance,
    SimpleAtmosphericCorrection,
    ToFloat32,
)
from geotoolz.restore import (
    MNF,
    BilateralDenoise,
    DenoisePCA,
    DespeckleFrost,
    DespeckleLee,
    DespeckleRefinedLee,
    DestripeColumn,
    GapFillIDW,
    GapFillInpaintBiharmonic,
    GapFillLaplacian,
    GapFillNearest,
    GaussianDenoise,
    InverseMNF,
    MedianDenoise,
    MomentMatching,
    NLMeans,
    OutlierMask,
    ReplaceOutliers,
    SaturationFlag,
)
from geotoolz.types import GeoSlice
from geotoolz.viz import (
    AnnotatePoints,
    AnnotatePolygons,
    ApplyColormap,
    ApplyDiscreteColormap,
    Composite,
    FalseColor,
    GammaCorrect,
    Hillshade,
    Overlay,
    ShadedRelief,
    StretchToUint8,
    SWIRComposite,
    ToDisplayRange,
    TrueColor,
)


if TYPE_CHECKING:
    from geotoolz.catalog import (
        DuckDBGeoCatalog,
        build_vector_catalog,
        build_xarray_catalog,
        load_vector,
        load_xarray,
    )


_LAZY_TOP_ATTRS = (
    "build_xarray_catalog",
    "load_xarray",
    "build_vector_catalog",
    "load_vector",
    "DuckDBGeoCatalog",
)


def __getattr__(name: str) -> Any:
    """Lazy proxy for the extras-gated catalog backends at the top level."""
    if name in _LAZY_TOP_ATTRS:
        attr = getattr(catalog, name)
        globals()[name] = attr
        return attr
    raise AttributeError(f"module 'geotoolz' has no attribute {name!r}")


__version__ = "0.0.6"

__all__ = [
    "ARVI",
    "BAIS2",
    "BSI",
    "CIRI",
    "DOS1",
    "EVI",
    "EVI2",
    "GCI",
    "MNDWI",
    "MNF",
    "NBR",
    "NBR2",
    "NDBI",
    "NDMI",
    "NDSI",
    "NDVI",
    "NDWI",
    "SAVI",
    "SBMP",
    "SCL",
    "SCL_CLOUDS",
    "SCL_INVALID",
    "AnnotatePoints",
    "AnnotatePolygons",
    "AppendIndex",
    "ApplyColormap",
    "ApplyDiscreteColormap",
    "ApplyMask",
    "ApplySRF",
    "BTFromRadiance",
    "BilateralDenoise",
    "Branch",
    "Carrier",
    "CatalogDomain",
    "CatalogRow",
    "ClayMinerals",
    "ColumnToMass",
    "Composite",
    "ComputeSZA",
    "Const",
    "CrossSectionalFlux",
    "DNToRadiance",
    "DNToReflectance",
    "DenoisePCA",
    "DespeckleFrost",
    "DespeckleLee",
    "DespeckleRefinedLee",
    "DestripeColumn",
    "DuckDBGeoCatalog",
    "EarthSunDistanceCorrection",
    "FalseColor",
    "Fanout",
    "Gamma",
    "GammaCorrect",
    "GapFillIDW",
    "GapFillInpaintBiharmonic",
    "GapFillLaplacian",
    "GapFillNearest",
    "GaussianDenoise",
    "GeoCatalog",
    "GeoSlice",
    "Graph",
    "Hillshade",
    "IMEEstimate",
    "Identity",
    "InMemoryGeoCatalog",
    "Input",
    "IntegratedIrradiance",
    "InverseMNF",
    "IronOxide",
    "Lambda",
    "MaskFromQABits",
    "MaskFromSCL",
    "MaskValid",
    "MedianDenoise",
    "MinMax",
    "ModelOp",
    "MomentMatching",
    "NLMeans",
    "Node",
    "NormalizedDifference",
    "Operator",
    "OutlierMask",
    "Overlay",
    "PercentileClip",
    "PlumeContours",
    "PlumeFootprint",
    "PlumeMask",
    "RadianceToDN",
    "RadianceToReflectance",
    "ReflectanceToRadiance",
    "ReplaceOutliers",
    "SWIRComposite",
    "SaturationFlag",
    "Sequential",
    "ShadedRelief",
    "ShapeTrace",
    "SimpleAtmosphericCorrection",
    "Sink",
    "Snapshot",
    "StretchToUint8",
    "Switch",
    "Tap",
    "ToDisplayRange",
    "ToFloat32",
    "TrueColor",
    "WindAdvectionCone",
    "__version__",
    "augment",
    "build_raster_catalog",
    "build_vector_catalog",
    "build_xarray_catalog",
    "catalog",
    "cloud",
    "core",
    "dNBR",
    "from_geoparquet",
    "geom",
    "indices",
    "intersect",
    "io",
    "kNDVI",
    "load_raster",
    "load_raster_timeseries",
    "load_vector",
    "load_xarray",
    "mask",
    "normalize",
    "open_catalog",
    "plume",
    "qa",
    "query",
    "radiometry",
    "restore",
    "spectral",
    "to_geoparquet",
    "types",
    "union",
    "viz",
]
