"""Composable pure-NumPy matched-filter operators."""

from __future__ import annotations

from geotoolz.matched_filter._src.array import (
    AdaptiveBackground,
    ClusterBackground,
    NumpyLinearOperator,
    StreamingBackgroundResult,
    WelfordAccumulator,
    apply_image,
    apply_pixel,
    detection_threshold,
    estimate_cov_empirical,
    estimate_cov_lowrank,
    estimate_cov_shrunk,
    estimate_mean,
    matched_filter_snr,
    validate_mf_inputs,
)
from geotoolz.matched_filter._src.operators import (
    AdaptiveWindowBackground,
    ApplyClusterMF,
    ColumnEnhancement,
    DetectionThreshold,
    EstimateCovEmpirical,
    EstimateCovLowRank,
    EstimateCovShrunk,
    EstimateMean,
    GMMClusterBackground,
    LinearTargetFromObs,
    MatchedFilter,
    MatchedFilterPixel,
    MatchedFilterSNR,
    NonlinearTargetFromObs,
    StreamingBackground,
    ValidateMFInputs,
)


__all__ = [
    "AdaptiveBackground",
    "AdaptiveWindowBackground",
    "ApplyClusterMF",
    "ClusterBackground",
    "ColumnEnhancement",
    "DetectionThreshold",
    "EstimateCovEmpirical",
    "EstimateCovLowRank",
    "EstimateCovShrunk",
    "EstimateMean",
    "GMMClusterBackground",
    "LinearTargetFromObs",
    "MatchedFilter",
    "MatchedFilterPixel",
    "MatchedFilterSNR",
    "NonlinearTargetFromObs",
    "NumpyLinearOperator",
    "StreamingBackground",
    "StreamingBackgroundResult",
    "ValidateMFInputs",
    "WelfordAccumulator",
    "apply_image",
    "apply_pixel",
    "detection_threshold",
    "estimate_cov_empirical",
    "estimate_cov_lowrank",
    "estimate_cov_shrunk",
    "estimate_mean",
    "matched_filter_snr",
    "validate_mf_inputs",
]
