"""geotoolz — composable Operator library for remote sensing.

The composition core (`Operator`, `Sequential`, `Graph`, …) lives in
the carrier-agnostic [`pipekit`](https://github.com/jejjohnson/pipekit)
framework — `geotoolz` re-exports the common names at the top level and
adds the per-domain operator families (`radiometry`, `indices`, `qa`,
`mask`, …) on top.

    import geotoolz as gz
    pipe = gz.Sequential([gz.Tap(print), gz.Identity()])

Re-export policy: every public **Operator class** of every family
(including subnamespaces such as ``geom.coregister``) plus the ``SCL``
class sets and ``SENSOR_QA_REGISTRY`` is available at the top level;
the **Tier-A numpy primitives** (``ndvi``, ``apply_mask``,
``percentile_clip``, ...) and other helpers live in their submodules
only. Each public name has exactly one home family, so every top-level
name is unambiguous. ``tests/test_geotoolz.py::test_public_operators_exported``
enforces this; the only exceptions are:

- ``augment.Compose`` (a probability-gated ``Sequential`` of
  augmentations): at the top level it would sit next to pipekit's
  right-to-left ``compose`` and read as a generic composer, so it is
  spelled ``gz.augment.Compose``.
- ``io.SourceOperator`` / ``io.SinkOperator``: abstract base classes
  for writing new readers / writers (they have no ``_apply``), not
  pipeline steps, and ``SinkOperator`` would sit next to pipekit's
  ``Sink``. Subclass them from ``gz.io``.
- ``patch_ops``: an optional extra (below); ``import geotoolz`` must not
  require geopatcher, so its operators are only reachable as
  ``gz.patch_ops.*``.

The four-axis Patcher framework lives in the
[`geotoolz-patcher`](https://github.com/jejjohnson/geotoolz/tree/main/packages/geotoolz-patcher)
workspace package (import name `geopatcher`). Install
the optional `[patch]` extra (``pip install 'geotoolz[patch]'``) to pull
it in and use ``geotoolz.patch_ops`` for the Operator-graph bridge:

    import geopatcher as gp
    from geotoolz import Sequential
    from geotoolz.patch_ops import GridSampler, ApplyToChips, MergePatches

Product readers (``ProductReader`` and the per-sensor / per-provider
subpackages) live in the
[`geotoolz-products`](https://github.com/jejjohnson/geotoolz/tree/main/packages/geotoolz-products)
workspace package (import name `geoproducts`); their output is a
`GeoTensor` every operator here accepts.
"""

from __future__ import annotations

from pipekit import (
    Branch,
    Carrier,
    Const,
    Fanout,
    Graph,
    Identity,
    Input,
    Lambda,
    Node,
    Operator,
    Sequential,
    ShapeTrace,
    Sink,
    Snapshot,
    Switch,
    Tap,
)

from geotoolz import (
    augment,
    compositing,
    einx,
    feature,
    geom,
    indices,
    io,
    learn,
    mask,
    matched_filter,
    measure,
    normalize,
    plume,
    qa,
    radiometry,
    restore,
    segment,
    spectral,
    viz,
)
from geotoolz.augment import (
    AtmosphericHaze,
    BandDropout,
    BandJitter,
    BrightnessJitter,
    ContrastJitter,
    CutMix,
    GaussianNoise,
    RandomCrop,
    RandomFlip,
    RandomRotate90,
    RandomShift,
    SimulatedClouds,
    SpeckleNoise,
    SunAngleJitter,
)
from geotoolz.compositing import (
    BAPComposite,
    BlendMatched,
    CloudFreeComposite,
    MaxNDVIComposite,
    MedianComposite,
    MinCloudComposite,
    StackMatched,
)
from geotoolz.einx import (
    CHWtoHWC,
    Einx,
    HWCtoCHW,
    PerBandReduce,
    SpatialPool,
)
from geotoolz.feature import (
    HOG,
    BlobDOG,
    BlobDoH,
    BlobLoG,
    Canny,
    CornerHarris,
    HoughCircles,
    HoughLines,
    MultiscaleBasicFeatures,
    PeakLocalMax,
    StructureTensor,
)
from geotoolz.geom import (
    AntimeridianSplit,
    BowtieCorrection,
    CropTo,
    CropToBounds,
    Georeference,
    GeostationaryParallaxCorrect,
    Mosaic,
    OpticalFlowILK,
    OpticalFlowTVL1,
    PadTo,
    PhaseAlign,
    Rasterize,
    RasterizeLike,
    Reproject,
    ReprojectLike,
    Resample,
    ResampleLike,
    Resize,
    SegmentStitch,
    SlidingWindow,
    Stitch,
    Tile,
    Vectorize,
)
from geotoolz.geom.coregister import (
    PointCloudToRaster,
    PointsToRaster,
    RasterToPointCloud,
    RasterToPoints,
    RasterToRasterLike,
    VectorToRasterAgg,
)
from geotoolz.indices import (
    ARVI,
    BAIS2,
    BSI,
    CIRI,
    EVI,
    EVI2,
    GCI,
    MNDWI,
    NBR,
    NBR2,
    NDBI,
    NDMI,
    NDSI,
    NDVI,
    NDWI,
    SAVI,
    AppendIndex,
    ClayMinerals,
    IronOxide,
    NormalizedDifference,
    dNBR,
    kNDVI,
)
from geotoolz.io import (
    LoadFromEE,
    LoadFromSTAC,
    ReadBounds,
    ReadCenterCoords,
    ReadHDF,
    ReadNetCDF,
    ReadPolygon,
    ReadReprojectLike,
    ReadTile,
    ReadToCRS,
    ReadWindow,
    WriteCOG,
    WriteGeoTIFF,
    WriteZarr,
)
from geotoolz.learn import (
    GeoTensorEstimator,
    ModelOp,
    PixelwiseGMM,
    PixelwiseIPCA,
    PixelwiseIsolationForest,
    PixelwiseIterativeImputer,
    PixelwiseKMeans,
    PixelwiseKNNImputer,
    PixelwiseLocalOutlierFactor,
    PixelwiseMiniBatchKMeans,
    PixelwiseNMF,
    PixelwiseOneClassSVM,
    PixelwisePCA,
    SklearnOp,
)
from geotoolz.mask import (
    AltitudeMask,
    ApplyMask,
    BBoxMask,
    BufferMask,
    CleanMask,
    CloseMask,
    CombineMasks,
    CountryMask,
    DilateMask,
    DistanceMask,
    ErodeMask,
    InvertMask,
    LandMask,
    OceanMask,
    OpenMask,
    PolygonMask,
    RemoveSmallHoles,
    RemoveSmallObjects,
    SlopeMask,
)
from geotoolz.matched_filter import (
    AdaptiveWindowBackground,
    ApplyAdaptiveMF,
    ApplyClusterMF,
    ColumnEnhancement,
    DetectionThreshold,
    EstimateCovEmpirical,
    EstimateCovLowRank,
    EstimateCovShrunk,
    EstimateMean,
    GMMClusterBackground,
    LinearTargetFromObs,
    MatchedFilter,
    MatchedFilterPixel,
    MatchedFilterSNR,
    NonlinearTargetFromObs,
    StreamingBackground,
    ValidateMFInputs,
)
from geotoolz.measure import (
    RANSAC,
    FindContours,
    LabelConnectedComponents,
    ProfileLine,
    RegionProps,
    ShannonEntropy,
    SkeletonLength,
)
from geotoolz.normalize import (
    CLAHE,
    AsinhScale,
    HistogramMatch,
    HistogramStretch,
    LogScale,
    MinMaxScaler,
    Normalize,
    PerBandStats,
    PowerScale,
    RobustScaler,
    StandardScaler,
    ZeroOne,
)
from geotoolz.plume import (
    SBMP,
    ColumnToMass,
    CrossSectionalFlux,
    IMEEstimate,
    PlumeColumnStats,
    PlumeContours,
    PlumeFootprint,
    PlumeMask,
    PlumeQNDFeatures,
    PlumeShapeFilter,
    WindAdvectionCone,
)
from geotoolz.qa import (
    S2QA60,
    S2SCL,
    SCL,
    SCL_CLOUDS,
    SCL_CLOUDS_AND_INVALID,
    SCL_INVALID,
    SCL_LAND,
    SCL_WATER,
    SENSOR_QA_REGISTRY,
    CloudSEN12,
    DecodeBitmask,
    LandsatQA_PIXEL,
    MaskCirrus,
    MaskClouds,
    MaskCloudShadow,
    MaskInvalid,
    MaskNoData,
    MaskSaturated,
    MaskSnow,
    MaskWater,
    MODISStateQA,
    OmniCloudMask,
    S2Cloudless,
)
from geotoolz.radiometry import (
    DOS1,
    ApplySRF,
    BTFromRadiance,
    ComputeSZA,
    DNToRadiance,
    DNToReflectance,
    EarthSunDistanceCorrection,
    Gamma,
    IntegratedIrradiance,
    MinMax,
    PercentileClip,
    RadianceToDN,
    RadianceToReflectance,
    ReflectanceToRadiance,
    SimpleAtmosphericCorrection,
    ToFloat32,
)
from geotoolz.restore import (
    MNF,
    BilateralDenoise,
    DenoisePCA,
    DespeckleFrost,
    DespeckleLee,
    DespeckleRefinedLee,
    DestripeColumn,
    GapFillIDW,
    GapFillInpaintBiharmonic,
    GapFillLaplacian,
    GapFillNearest,
    GaussianDenoise,
    MedianDenoise,
    MomentMatching,
    NLMeans,
    OutlierMask,
    ReplaceOutliers,
)
from geotoolz.segment import (
    SLIC,
    ChanVese,
    ExpandLabels,
    Felzenszwalb,
    MarkBoundaries,
    MaskNMS,
    MergeNearbyInstances,
    Quickshift,
    RandomWalker,
    Threshold,
    Watershed,
)
from geotoolz.spectral import (
    BandMath,
    BandRatio,
    ContinuumRemoval,
    ReorderBands,
    SelectBands,
    SpectralBinning,
    SpectralSmoothing,
    SplitBands,
    StackBands,
)
from geotoolz.viz import (
    AnnotatePoints,
    AnnotatePolygons,
    ApplyColormap,
    ApplyDiscreteColormap,
    Composite,
    FalseColor,
    GammaCorrect,
    Hillshade,
    Overlay,
    RGBRecipe,
    ShadedRelief,
    StretchToUint8,
    SWIRComposite,
    TrueColor,
)


__version__ = "0.8.0"

__all__ = [
    "ARVI",
    "BAIS2",
    "BSI",
    "CIRI",
    "CLAHE",
    "DOS1",
    "EVI",
    "EVI2",
    "GCI",
    "HOG",
    "MNDWI",
    "MNF",
    "NBR",
    "NBR2",
    "NDBI",
    "NDMI",
    "NDSI",
    "NDVI",
    "NDWI",
    "RANSAC",
    "S2QA60",
    "S2SCL",
    "SAVI",
    "SBMP",
    "SCL",
    "SCL_CLOUDS",
    "SCL_CLOUDS_AND_INVALID",
    "SCL_INVALID",
    "SCL_LAND",
    "SCL_WATER",
    "SENSOR_QA_REGISTRY",
    "SLIC",
    "AdaptiveWindowBackground",
    "AltitudeMask",
    "AnnotatePoints",
    "AnnotatePolygons",
    "AntimeridianSplit",
    "AppendIndex",
    "ApplyAdaptiveMF",
    "ApplyClusterMF",
    "ApplyColormap",
    "ApplyDiscreteColormap",
    "ApplyMask",
    "ApplySRF",
    "AsinhScale",
    "AtmosphericHaze",
    "BAPComposite",
    "BBoxMask",
    "BTFromRadiance",
    "BandDropout",
    "BandJitter",
    "BandMath",
    "BandRatio",
    "BilateralDenoise",
    "BlendMatched",
    "BlobDOG",
    "BlobDoH",
    "BlobLoG",
    "BowtieCorrection",
    "Branch",
    "BrightnessJitter",
    "BufferMask",
    "CHWtoHWC",
    "Canny",
    "Carrier",
    "ChanVese",
    "ClayMinerals",
    "CleanMask",
    "CloseMask",
    "CloudFreeComposite",
    "CloudSEN12",
    "ColumnEnhancement",
    "ColumnToMass",
    "CombineMasks",
    "Composite",
    "ComputeSZA",
    "Const",
    "ContinuumRemoval",
    "ContrastJitter",
    "CornerHarris",
    "CountryMask",
    "CropTo",
    "CropToBounds",
    "CrossSectionalFlux",
    "CutMix",
    "DNToRadiance",
    "DNToReflectance",
    "DecodeBitmask",
    "DenoisePCA",
    "DespeckleFrost",
    "DespeckleLee",
    "DespeckleRefinedLee",
    "DestripeColumn",
    "DetectionThreshold",
    "DilateMask",
    "DistanceMask",
    "EarthSunDistanceCorrection",
    "Einx",
    "ErodeMask",
    "EstimateCovEmpirical",
    "EstimateCovLowRank",
    "EstimateCovShrunk",
    "EstimateMean",
    "ExpandLabels",
    "FalseColor",
    "Fanout",
    "Felzenszwalb",
    "FindContours",
    "GMMClusterBackground",
    "Gamma",
    "GammaCorrect",
    "GapFillIDW",
    "GapFillInpaintBiharmonic",
    "GapFillLaplacian",
    "GapFillNearest",
    "GaussianDenoise",
    "GaussianNoise",
    "GeoTensorEstimator",
    "Georeference",
    "GeostationaryParallaxCorrect",
    "Graph",
    "HWCtoCHW",
    "Hillshade",
    "HistogramMatch",
    "HistogramStretch",
    "HoughCircles",
    "HoughLines",
    "IMEEstimate",
    "Identity",
    "Input",
    "IntegratedIrradiance",
    "InvertMask",
    "IronOxide",
    "LabelConnectedComponents",
    "Lambda",
    "LandMask",
    "LandsatQA_PIXEL",
    "LinearTargetFromObs",
    "LoadFromEE",
    "LoadFromSTAC",
    "LogScale",
    "MODISStateQA",
    "MarkBoundaries",
    "MaskCirrus",
    "MaskCloudShadow",
    "MaskClouds",
    "MaskInvalid",
    "MaskNMS",
    "MaskNoData",
    "MaskSaturated",
    "MaskSnow",
    "MaskWater",
    "MatchedFilter",
    "MatchedFilterPixel",
    "MatchedFilterSNR",
    "MaxNDVIComposite",
    "MedianComposite",
    "MedianDenoise",
    "MergeNearbyInstances",
    "MinCloudComposite",
    "MinMax",
    "MinMaxScaler",
    "ModelOp",
    "MomentMatching",
    "Mosaic",
    "MultiscaleBasicFeatures",
    "NLMeans",
    "Node",
    "NonlinearTargetFromObs",
    "Normalize",
    "NormalizedDifference",
    "OceanMask",
    "OmniCloudMask",
    "OpenMask",
    "Operator",
    "OpticalFlowILK",
    "OpticalFlowTVL1",
    "OutlierMask",
    "Overlay",
    "PadTo",
    "PeakLocalMax",
    "PerBandReduce",
    "PerBandStats",
    "PercentileClip",
    "PhaseAlign",
    "PixelwiseGMM",
    "PixelwiseIPCA",
    "PixelwiseIsolationForest",
    "PixelwiseIterativeImputer",
    "PixelwiseKMeans",
    "PixelwiseKNNImputer",
    "PixelwiseLocalOutlierFactor",
    "PixelwiseMiniBatchKMeans",
    "PixelwiseNMF",
    "PixelwiseOneClassSVM",
    "PixelwisePCA",
    "PlumeColumnStats",
    "PlumeContours",
    "PlumeFootprint",
    "PlumeMask",
    "PlumeQNDFeatures",
    "PlumeShapeFilter",
    "PointCloudToRaster",
    "PointsToRaster",
    "PolygonMask",
    "PowerScale",
    "ProfileLine",
    "Quickshift",
    "RGBRecipe",
    "RadianceToDN",
    "RadianceToReflectance",
    "RandomCrop",
    "RandomFlip",
    "RandomRotate90",
    "RandomShift",
    "RandomWalker",
    "RasterToPointCloud",
    "RasterToPoints",
    "RasterToRasterLike",
    "Rasterize",
    "RasterizeLike",
    "ReadBounds",
    "ReadCenterCoords",
    "ReadHDF",
    "ReadNetCDF",
    "ReadPolygon",
    "ReadReprojectLike",
    "ReadTile",
    "ReadToCRS",
    "ReadWindow",
    "ReflectanceToRadiance",
    "RegionProps",
    "RemoveSmallHoles",
    "RemoveSmallObjects",
    "ReorderBands",
    "ReplaceOutliers",
    "Reproject",
    "ReprojectLike",
    "Resample",
    "ResampleLike",
    "Resize",
    "RobustScaler",
    "S2Cloudless",
    "SWIRComposite",
    "SegmentStitch",
    "SelectBands",
    "Sequential",
    "ShadedRelief",
    "ShannonEntropy",
    "ShapeTrace",
    "SimpleAtmosphericCorrection",
    "SimulatedClouds",
    "Sink",
    "SkeletonLength",
    "SklearnOp",
    "SlidingWindow",
    "SlopeMask",
    "Snapshot",
    "SpatialPool",
    "SpeckleNoise",
    "SpectralBinning",
    "SpectralSmoothing",
    "SplitBands",
    "StackBands",
    "StackMatched",
    "StandardScaler",
    "Stitch",
    "StreamingBackground",
    "StretchToUint8",
    "StructureTensor",
    "SunAngleJitter",
    "Switch",
    "Tap",
    "Threshold",
    "Tile",
    "ToFloat32",
    "TrueColor",
    "ValidateMFInputs",
    "VectorToRasterAgg",
    "Vectorize",
    "Watershed",
    "WindAdvectionCone",
    "WriteCOG",
    "WriteGeoTIFF",
    "WriteZarr",
    "ZeroOne",
    "__version__",
    "augment",
    "compositing",
    "dNBR",
    "einx",
    "feature",
    "geom",
    "indices",
    "io",
    "kNDVI",
    "learn",
    "mask",
    "matched_filter",
    "measure",
    "normalize",
    "plume",
    "qa",
    "radiometry",
    "restore",
    "segment",
    "spectral",
    "viz",
]
